daniel_security_user_login:
    path:     /user/login
    defaults: { _controller: DanielSecurityBundle:User:login }
daniel_security_user_register:
    path: /user/register
    defaults: { _controller: DanielSecurityBundle:User:register }