# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    # añadir codificación bcrypt para nuestra entidad
    encoders:
        Daniel\SecurityBundle\Entity\User:
            algorithm: bcrypt
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        my_user_provider:
            entity:
                class: DanielSecurityBundle:User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern: ^/
            provider: my_user_provider
            form_login:
                login_path: /login
                check_path: security_user_login_check
            logout:
                path: /logout
                target: /
    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ['ROLE_USER', 'ROLE_ADMIN']}